### ISSUE TITLE
2.1.0 breaks TS build

### ISSUE THREAD

**Issue by mmouterde** [simonplend/express-json-validator-middleware#39] opened 2020-03-22 22:27 UTC
2.0.0 works great but once updated to 2.1.0 I got strange errors from ts compiler.

```
Type '{ type: string; required: string[]; properties: { firstName: { type: string; }; lastName: { type: string; }; email: { type: string; }; phone: { type: string[]; }; password: { type: string; }; participantId: { type: string; }; }; }' is not assignable to type 'ValidateFunction'.
  Type '{ type: string; required: string[]; properties: { firstName: { type: string; }; lastName: { type: string; }; email: { type: string; }; phone: { type: string[]; }; password: { type: string; }; participantId: { type: string; }; }; }' is not assignable to type 'JSONSchema7'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" | "integer" | "null" | "array" | JSONSchema7TypeName[]'.
```

**Comment by JouzaLoL** [comment] 2020-03-24 21:46
I will look into it ASAP.

**Comment by JouzaLoL** [comment] 2020-03-27 15:55
Can you please provide a minimal reproduction repo or example?

**Comment by mmouterde** [comment] 2020-03-28 12:58
sure https://github.com/mmouterde/bugDemo
~~~
import { Validator } from 'express-json-validator-middleware';
const UserParamSchemaForUpdate = {
    type: 'object',
    properties: {
        firstName: { type: 'string' }
    },
};
const validator = new Validator({
    allErrors: true,
    format: 'full',
    jsonPointers: true,
});
validator.validate({
    body: UserParamSchemaForUpdate,
});
~~~

**Comment by rmolinamir** [comment] 2020-04-06 20:06
Basically `body` is not compatible with objects unless explicitly specified such as:

```ts
app.post('/template', validate({ body: schemas.templateCreate as ValidateFunction }), templateController.create_template);
```

**Comment by monooso** [comment] 2020-09-15 15:42
@vacekj I'm having the same problem. I'm not sure what @rmolinamir is referring to, but it doesn't appear to relate to the original issue.

The following example uses the schema from the README:

```js
import { Validator } from 'express-json-validator-middleware'

const validator = new Validator({ allErrors: true })

const docsSchema = {
  type: 'object',
  required: ['number', 'name', 'type'],
  properties: {
    number: { type: 'number' },
    name: { type: 'string' },
    type: { type: 'string', enum: ['Street', 'Avenue', 'Boulevard'] },
  },
}

validator.validate({ body: docsSchema })
```

**Comment by senorpedro** [comment] 2020-10-23 15:15
I experienced the same issue, what worked for me was to put `as const` after the type value, e.g. 
```javascript
{
  type: 'object' as const
 ...
}
```

unfortunately this meant not being able to use .json files anymore, had to migrate them to TS

**Comment by simonplend** [comment] 2021-01-19 13:14
Hi folks :wave: I'm the new maintainer of this project.

I've just started looking into this issue and will attempt to reproduce it. I'll let you know how I get on, but any further insights as to what the issue might be are very welcome in the meantime!

**Comment by NGTOne** [comment] 2021-02-17 12:54
It looks like this issue was actually introduced by _adding_ types, period - `2.1.0` was the first package version to actually _have_ type definitions.

**Comment by simonplend** [comment] 2021-02-17 21:52
@NGTOne That makes sense. I think this issue needs to be resolved as removing the types completely isn't a viable option. I'm hoping to have time to do some digging on this later this week.

**Comment by simonplend** [comment] 2021-05-23 14:32
I've been trying to resolve this issue, but it's proving tricky. I've created a minimal reproducible example demonstrating the problem: https://bit.ly/3oIwQ9z (thanks to @monooso for sharing their workaround above).

**Comment by Beraliv** [comment] 2021-05-23 16:01
@simonplend  You need to use `as const` to make `object` a string literal:

It works good here: https://tsplay.dev/WJ96lm

**Comment by simonplend** [comment] 2021-05-23 17:02
@Beraliv That's great, thank you! It seems similar to the solution which @senorpedro [mentioned above](https://github.com/simonplend/express-json-validator-middleware/issues/39#issuecomment-715405265).

This raises a couple of questions for me:

- Why does making `object` a string literal fix things?
- Is it preferable to put `as const` after the `object` string, or after the whole object itself?

I really appreciate everyone's help with this issue. I only have a little experience with TypeScript, and I want to make sure I resolve this issue correctly, even if it just means adding a section to the README with some guidance on using this library with TypeScript.

**Comment by Beraliv** [comment] 2021-05-23 17:33
> Why does making `object` a string literal fix things?

I checked the `validate` function implementation and found string literals there:

1. Open https://github.com/simonplend/express-json-validator-middleware/blob/main/src/index.d.ts#L27
2. It uses `ValidatorFunction` – https://github.com/simonplend/express-json-validator-middleware/blob/main/src/index.d.ts#L18-L20
3. Inside it uses `AllowedSchema` – https://github.com/simonplend/express-json-validator-middleware/blob/main/src/index.d.ts#L13-L16
4. Inside `JSONSchema7` you will find `type` – https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/json-schema/index.d.ts#L627
5. This type should be a string literal – https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/json-schema/index.d.ts#L570-L577

Check out the example here: https://tsplay.dev/wee2Ew

1. If you inline the code, it will infer string as a string literal (and you will have no error)
2. If you use `as const` either for object or for a string, it will convert the string to string literal and you will have no error too

You need `as const` because of the way how you declared the type:

```ts
type ValidateParameters = { type: 'object', parameters: Record<string, unknown> } | { type: 'string'; parameters: string; };
```

If you use `'object'` in `type` or `interface`, it means you use string literals and you require to pass it from outside the same way (as string literal)

> Is it preferable to put `as const` after the `object` string, or after the whole object itself?

It you call `as const` on the whole object, all strings inside will become string literals. But if you have at least one string literal inside you schema (e.g. `JSONSchema7`), `as const` for the whole object will be helpful and easy way to fix the problem:
1. If you have `string` in types, both string literal and string can be passed
2. If you have string literal in types, only this string literal can be passed

You can check examples here: https://tsplay.dev/wj53YW

**Comment by simonplend** [comment] 2021-05-23 19:38
@Beraliv Thank you so much for this detailed detective work, the thorough explanation, and for all of the examples too. They are really helpful.

I think I understand everything you've explained, but I'm going to read it all again with fresh eyes tomorrow.

I'm planning to add a short section to the project README with tips on usage with TypeScript. If you are happy to, I would really appreciate you looking over these documentation changes before I merge them. Would you mind me tagging you in the PR?

**Comment by Beraliv** [comment] 2021-05-23 23:32
> Would you mind me tagging you in the PR?

Not at all, I'm fine with it 👍

**Comment by Beraliv** [comment] 2021-06-06 10:57
@simonplend do you still need help?

**Comment by simonplend** [comment] 2021-08-03 20:48
@Beraliv I've added a section to the README explaining how to define schemas in TypeScript. If you're still happy to, I'd be very grateful if you could review these changes for accuracy: https://github.com/simonplend/express-json-validator-middleware/pull/89

**Comment by simonplend** [comment] 2021-08-03 20:52
I was looking at the documentation for the [json-schema-to-ts](https://www.npmjs.com/package/json-schema-to-ts) package recently. I noticed their documentation also mentions the need to use `as const` when defining JSON schemas in TypeScript: https://www.npmjs.com/package/json-schema-to-ts#fromschema

**Comment by Beraliv** [comment] 2021-08-03 20:55
> @Beraliv I've added a section to the README explaining how to define schemas in TypeScript. If you're still happy to, I'd be very grateful if you could review these changes for accuracy: https://github.com/simonplend/express-json-validator-middleware/pull/89

Sure, I can check it tomorrow

**Comment by simonplend** [comment] 2021-08-09 21:03
I'm planning to merge #89 tomorrow so that I can close this issue and get v2.2.0 released.

Thanks for your help everyone!

**Closed** 2021-08-10 11:52 UTC
Labels: bug, help wanted
